### PR TITLE
Upgrade to Livewire 3

### PR DESCRIPTION
**Pull request by danharrin**
~~This PR needs targeting at a new `3.x` branch instead of `2.x`.~~

### CODE REVIEW

**Comment by owenvoke** [comment]
Hmm, my only issue is that the branch versions / plugin versions are intended to match the Pest major versions.

@nunomaduro, what are your thoughts on this? 🤔 Unless we do some check for the version of Livewire you have installed, and switch between them?

**Comment by nunomaduro** [comment]
@danharrin Can you support both versions, doing something like a `class_exists`, and define the trait witin the if and else??

**Comment by danharrin** [comment]
Oh sorry, I thought the branching strategy matched Livewire. I can try the conditional approach, yeah

**Comment by danharrin** [comment]
Alright it should be ok now 👍 Not worth merging before LW3 release as the tests will fail.

**Review by owenvoke — APPROVED** [review]

**Comment by zepfietje** [comment]
This should be ready for merge now.

**Pull request merged**
